/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const feeds_Logic = require('./code/feeds-logic');

class TestEYShareService extends LCAPApplicationService {
    async init() {

        this.on('READ', 'feeds', async (request, next) => {
            await feeds_Logic({
                request
            });
            return next();
        });
        var i=0;
        this.after ('READ','wall', each => {
            console.log(`this is inside wall`);
          })
        return super.init();
    }
}


module.exports = {
    TestEYShareService
};