/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const wall_Logic = require('./code/wall-logic');

class TestEYShare extends LCAPApplicationService {
    async init() {

        this.before('READ', 'wall', async (request) => {
            await wall_Logic({
                request
            });
        });

        return super.init();
    }
}


module.exports = {
    TestEYShare
};